# Generated by Django 3.0.4 on 2020-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='car_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_id',
            field=models.CharField(max_length=200),
        ),
    ]
