# Generated by Django 3.0.4 on 2020-05-12 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200429_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whrite_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('text_area', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photos/blog/%Y/%m/%d')),
            ],
        ),
    ]
